# permissions for end users to edit upgradejobhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: upgradejobhook-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openshift-upgrade-controller
    app.kubernetes.io/part-of: openshift-upgrade-controller
    app.kubernetes.io/managed-by: kustomize
  name: upgradejobhook-editor-role
rules:
- apiGroups:
  - managedupgrade.appuio.io
  resources:
  - upgradejobhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managedupgrade.appuio.io
  resources:
  - upgradejobhooks/status
  verbs:
  - get
