apiVersion: managedupgrade.appuio.io/v1beta1
kind: ClusterVersion
metadata:
  name: version
spec:
  overlays:
    - from: '2024-08-08T03:00:00Z'
      overlay:
        spec:
          channel: stable-4.15
  template:
    spec:
      channel: stable-4.14
      clusterID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      upstream: 'https://api.openshift.com/api/upgrades_info/v1/graph'
status: {}
