apiVersion: managedupgrade.appuio.io/v1beta1
kind: UpgradeConfig
metadata:
  name: upgradeconfig-sample
spec:
  maxSchedulingDelay: 1h
  maxUpgradeStartDelay: 1h
  schedule:
    cron: "0 10 * * 2"
    location: Europe/Zurich
    suspend: false
  jobTemplate:
    metadata:
      labels:
        upgradeconfig/name: upgradeconfig-sample
    spec:
      config:
        upgradeTimeout: 12h
        preUpgradeHealthChecks:
          timeout: 1h
        postUpgradeHealthChecks:
          timeout: 1h
