apiVersion: managedupgrade.appuio.io/v1beta1
kind: UpgradeJobHook
metadata:
  name: upgradejobhook-sample
spec:
  events:
    - Create
    - Start
    - UpgradeComplete
    - Finish
    - Success
    - Failure
  run: Next # [Next, All]
  failurePolicy: Ignore # [Abort, Ignore]
  selector:
    matchLabels:
      upgradeconfig/name: upgradeconfig-sample
  template:
    spec:
      template:
        spec:
          containers:
          - name: notify
            image: curlimages/curl:8.1.2 # sponsored OSS image
            args:
            - -XPOST
            - -H
            - 'Content-Type: application/json'
            - -d
            - '{"event": $(EVENT_NAME), "version": $(JOB_spec_desiredVersion_image)}'
            - https://example.com/webhook
          restartPolicy: Never
      backoffLimit: 3
      ttlSecondsAfterFinished: 43200 # 12h
      activeDeadlineSeconds: 300 # 5m
