//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	configv1 "github.com/openshift/api/config/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimReference) DeepCopyInto(out *ClaimReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimReference.
func (in *ClaimReference) DeepCopy() *ClaimReference {
	if in == nil {
		return nil
	}
	out := new(ClaimReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersion) DeepCopyInto(out *ClusterVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersion.
func (in *ClusterVersion) DeepCopy() *ClusterVersion {
	if in == nil {
		return nil
	}
	out := new(ClusterVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionList) DeepCopyInto(out *ClusterVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionList.
func (in *ClusterVersionList) DeepCopy() *ClusterVersionList {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionOverlay) DeepCopyInto(out *ClusterVersionOverlay) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionOverlay.
func (in *ClusterVersionOverlay) DeepCopy() *ClusterVersionOverlay {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionOverlayConfig) DeepCopyInto(out *ClusterVersionOverlayConfig) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	in.Overlay.DeepCopyInto(&out.Overlay)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionOverlayConfig.
func (in *ClusterVersionOverlayConfig) DeepCopy() *ClusterVersionOverlayConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionOverlayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionSpec) DeepCopyInto(out *ClusterVersionSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.Overlays != nil {
		in, out := &in.Overlays, &out.Overlays
		*out = make([]ClusterVersionOverlayConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionSpec.
func (in *ClusterVersionSpec) DeepCopy() *ClusterVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionStatus) DeepCopyInto(out *ClusterVersionStatus) {
	*out = *in
	in.Current.DeepCopyInto(&out.Current)
	if in.Overlays != nil {
		in, out := &in.Overlays, &out.Overlays
		*out = make([]ClusterVersionStatusOverlays, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.OverlayApplied.DeepCopyInto(&out.OverlayApplied)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionStatus.
func (in *ClusterVersionStatus) DeepCopy() *ClusterVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionStatusOverlays) DeepCopyInto(out *ClusterVersionStatusOverlays) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	in.Preview.DeepCopyInto(&out.Preview)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionStatusOverlays.
func (in *ClusterVersionStatusOverlays) DeepCopy() *ClusterVersionStatusOverlays {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionStatusOverlays)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionStatusPreview) DeepCopyInto(out *ClusterVersionStatusPreview) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionStatusPreview.
func (in *ClusterVersionStatusPreview) DeepCopy() *ClusterVersionStatusPreview {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionStatusPreview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionTemplate) DeepCopyInto(out *ClusterVersionTemplate) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionTemplate.
func (in *ClusterVersionTemplate) DeepCopy() *ClusterVersionTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigV1ClusterVersionSpec) DeepCopyInto(out *ConfigV1ClusterVersionSpec) {
	*out = *in
	if in.DesiredUpdate != nil {
		in, out := &in.DesiredUpdate, &out.DesiredUpdate
		*out = new(configv1.Update)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(configv1.ClusterVersionCapabilitiesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SignatureStores != nil {
		in, out := &in.SignatureStores, &out.SignatureStores
		*out = make([]configv1.SignatureStore, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]configv1.ComponentOverride, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigV1ClusterVersionSpec.
func (in *ConfigV1ClusterVersionSpec) DeepCopy() *ConfigV1ClusterVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigV1ClusterVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookJobTracker) DeepCopyInto(out *HookJobTracker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookJobTracker.
func (in *HookJobTracker) DeepCopy() *HookJobTracker {
	if in == nil {
		return nil
	}
	out := new(HookJobTracker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextPossibleSchedule) DeepCopyInto(out *NextPossibleSchedule) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextPossibleSchedule.
func (in *NextPossibleSchedule) DeepCopy() *NextPossibleSchedule {
	if in == nil {
		return nil
	}
	out := new(NextPossibleSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeForceDrain) DeepCopyInto(out *NodeForceDrain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeForceDrain.
func (in *NodeForceDrain) DeepCopy() *NodeForceDrain {
	if in == nil {
		return nil
	}
	out := new(NodeForceDrain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeForceDrain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeForceDrainList) DeepCopyInto(out *NodeForceDrainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeForceDrain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeForceDrainList.
func (in *NodeForceDrainList) DeepCopy() *NodeForceDrainList {
	if in == nil {
		return nil
	}
	out := new(NodeForceDrainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeForceDrainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeForceDrainSpec) DeepCopyInto(out *NodeForceDrainSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.NodeDrainGracePeriod = in.NodeDrainGracePeriod
	out.PodForceDeleteGracePeriod = in.PodForceDeleteGracePeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeForceDrainSpec.
func (in *NodeForceDrainSpec) DeepCopy() *NodeForceDrainSpec {
	if in == nil {
		return nil
	}
	out := new(NodeForceDrainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeForceDrainStatus) DeepCopyInto(out *NodeForceDrainStatus) {
	*out = *in
	if in.LastObservedNodeDrain != nil {
		in, out := &in.LastObservedNodeDrain, &out.LastObservedNodeDrain
		*out = make([]ObservedNodeDrain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeForceDrainStatus.
func (in *NodeForceDrainStatus) DeepCopy() *NodeForceDrainStatus {
	if in == nil {
		return nil
	}
	out := new(NodeForceDrainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedNodeDrain) DeepCopyInto(out *ObservedNodeDrain) {
	*out = *in
	in.ObservedTime.DeepCopyInto(&out.ObservedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedNodeDrain.
func (in *ObservedNodeDrain) DeepCopy() *ObservedNodeDrain {
	if in == nil {
		return nil
	}
	out := new(ObservedNodeDrain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfig) DeepCopyInto(out *UpgradeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfig.
func (in *UpgradeConfig) DeepCopy() *UpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfigJobTemplate) DeepCopyInto(out *UpgradeConfigJobTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfigJobTemplate.
func (in *UpgradeConfigJobTemplate) DeepCopy() *UpgradeConfigJobTemplate {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfigJobTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfigJobTemplateSpec) DeepCopyInto(out *UpgradeConfigJobTemplateSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfigJobTemplateSpec.
func (in *UpgradeConfigJobTemplateSpec) DeepCopy() *UpgradeConfigJobTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfigJobTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfigList) DeepCopyInto(out *UpgradeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfigList.
func (in *UpgradeConfigList) DeepCopy() *UpgradeConfigList {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfigSchedule) DeepCopyInto(out *UpgradeConfigSchedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfigSchedule.
func (in *UpgradeConfigSchedule) DeepCopy() *UpgradeConfigSchedule {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfigSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfigSpec) DeepCopyInto(out *UpgradeConfigSpec) {
	*out = *in
	out.Schedule = in.Schedule
	out.PinVersionWindow = in.PinVersionWindow
	out.MaxSchedulingDelay = in.MaxSchedulingDelay
	out.MaxUpgradeStartDelay = in.MaxUpgradeStartDelay
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int)
		**out = **in
	}
	in.JobTemplate.DeepCopyInto(&out.JobTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfigSpec.
func (in *UpgradeConfigSpec) DeepCopy() *UpgradeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfigStatus) DeepCopyInto(out *UpgradeConfigStatus) {
	*out = *in
	if in.LastScheduledUpgrade != nil {
		in, out := &in.LastScheduledUpgrade, &out.LastScheduledUpgrade
		*out = (*in).DeepCopy()
	}
	if in.NextPossibleSchedules != nil {
		in, out := &in.NextPossibleSchedules, &out.NextPossibleSchedules
		*out = make([]NextPossibleSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfigStatus.
func (in *UpgradeConfigStatus) DeepCopy() *UpgradeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJob) DeepCopyInto(out *UpgradeJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJob.
func (in *UpgradeJob) DeepCopy() *UpgradeJob {
	if in == nil {
		return nil
	}
	out := new(UpgradeJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobConfig) DeepCopyInto(out *UpgradeJobConfig) {
	*out = *in
	out.UpgradeTimeout = in.UpgradeTimeout
	out.PreUpgradeHealthChecks = in.PreUpgradeHealthChecks
	out.PostUpgradeHealthChecks = in.PostUpgradeHealthChecks
	if in.MachineConfigPools != nil {
		in, out := &in.MachineConfigPools, &out.MachineConfigPools
		*out = make([]UpgradeJobMachineConfigPoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobConfig.
func (in *UpgradeJobConfig) DeepCopy() *UpgradeJobConfig {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobHealthCheck) DeepCopyInto(out *UpgradeJobHealthCheck) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobHealthCheck.
func (in *UpgradeJobHealthCheck) DeepCopy() *UpgradeJobHealthCheck {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobHook) DeepCopyInto(out *UpgradeJobHook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobHook.
func (in *UpgradeJobHook) DeepCopy() *UpgradeJobHook {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeJobHook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobHookList) DeepCopyInto(out *UpgradeJobHookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeJobHook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobHookList.
func (in *UpgradeJobHookList) DeepCopy() *UpgradeJobHookList {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobHookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeJobHookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobHookSpec) DeepCopyInto(out *UpgradeJobHookSpec) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]UpgradeEvent, len(*in))
		copy(*out, *in)
	}
	in.Selector.DeepCopyInto(&out.Selector)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobHookSpec.
func (in *UpgradeJobHookSpec) DeepCopy() *UpgradeJobHookSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobHookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobHookStatus) DeepCopyInto(out *UpgradeJobHookStatus) {
	*out = *in
	out.ClaimedBy = in.ClaimedBy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobHookStatus.
func (in *UpgradeJobHookStatus) DeepCopy() *UpgradeJobHookStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobHookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobList) DeepCopyInto(out *UpgradeJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobList.
func (in *UpgradeJobList) DeepCopy() *UpgradeJobList {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobMachineConfigPoolDelayUpgradeSpec) DeepCopyInto(out *UpgradeJobMachineConfigPoolDelayUpgradeSpec) {
	*out = *in
	out.DelayMin = in.DelayMin
	out.DelayMax = in.DelayMax
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobMachineConfigPoolDelayUpgradeSpec.
func (in *UpgradeJobMachineConfigPoolDelayUpgradeSpec) DeepCopy() *UpgradeJobMachineConfigPoolDelayUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobMachineConfigPoolDelayUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobMachineConfigPoolSpec) DeepCopyInto(out *UpgradeJobMachineConfigPoolSpec) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.DelayUpgrade = in.DelayUpgrade
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobMachineConfigPoolSpec.
func (in *UpgradeJobMachineConfigPoolSpec) DeepCopy() *UpgradeJobMachineConfigPoolSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobMachineConfigPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobSpec) DeepCopyInto(out *UpgradeJobSpec) {
	*out = *in
	in.StartAfter.DeepCopyInto(&out.StartAfter)
	in.StartBefore.DeepCopyInto(&out.StartBefore)
	if in.DesiredVersion != nil {
		in, out := &in.DesiredVersion, &out.DesiredVersion
		*out = new(configv1.Update)
		**out = **in
	}
	if in.DesiredVersionCheckAvailability != nil {
		in, out := &in.DesiredVersionCheckAvailability, &out.DesiredVersionCheckAvailability
		*out = new(bool)
		**out = **in
	}
	in.UpgradeJobConfig.DeepCopyInto(&out.UpgradeJobConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobSpec.
func (in *UpgradeJobSpec) DeepCopy() *UpgradeJobSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeJobStatus) DeepCopyInto(out *UpgradeJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HookJobTracker != nil {
		in, out := &in.HookJobTracker, &out.HookJobTracker
		*out = make([]HookJobTracker, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeJobStatus.
func (in *UpgradeJobStatus) DeepCopy() *UpgradeJobStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSuspensionWindow) DeepCopyInto(out *UpgradeSuspensionWindow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSuspensionWindow.
func (in *UpgradeSuspensionWindow) DeepCopy() *UpgradeSuspensionWindow {
	if in == nil {
		return nil
	}
	out := new(UpgradeSuspensionWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeSuspensionWindow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSuspensionWindowList) DeepCopyInto(out *UpgradeSuspensionWindowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeSuspensionWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSuspensionWindowList.
func (in *UpgradeSuspensionWindowList) DeepCopy() *UpgradeSuspensionWindowList {
	if in == nil {
		return nil
	}
	out := new(UpgradeSuspensionWindowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeSuspensionWindowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSuspensionWindowSpec) DeepCopyInto(out *UpgradeSuspensionWindowSpec) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
	if in.ConfigSelector != nil {
		in, out := &in.ConfigSelector, &out.ConfigSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.JobSelector != nil {
		in, out := &in.JobSelector, &out.JobSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSuspensionWindowSpec.
func (in *UpgradeSuspensionWindowSpec) DeepCopy() *UpgradeSuspensionWindowSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeSuspensionWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSuspensionWindowStatus) DeepCopyInto(out *UpgradeSuspensionWindowStatus) {
	*out = *in
	if in.MatchingConfigs != nil {
		in, out := &in.MatchingConfigs, &out.MatchingConfigs
		*out = make([]UpgradeSuspensionWindowStatusMatchingObject, len(*in))
		copy(*out, *in)
	}
	if in.MatchingJobs != nil {
		in, out := &in.MatchingJobs, &out.MatchingJobs
		*out = make([]UpgradeSuspensionWindowStatusMatchingObject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSuspensionWindowStatus.
func (in *UpgradeSuspensionWindowStatus) DeepCopy() *UpgradeSuspensionWindowStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeSuspensionWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSuspensionWindowStatusMatchingObject) DeepCopyInto(out *UpgradeSuspensionWindowStatusMatchingObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSuspensionWindowStatusMatchingObject.
func (in *UpgradeSuspensionWindowStatusMatchingObject) DeepCopy() *UpgradeSuspensionWindowStatusMatchingObject {
	if in == nil {
		return nil
	}
	out := new(UpgradeSuspensionWindowStatusMatchingObject)
	in.DeepCopyInto(out)
	return out
}
