name: Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release:
    name: Release
    uses: ./.github/workflows/tooling-release.yml
    permissions:
      contents: write # Required to publish a release
      packages: write # Required to push the docker images
    with:
      goreleaser-version: "2.16.0"
